import * as fs from "fs";
import * as path from "path";
import * as vscode from "vscode";
import { buildCommerceMcpCursorRule } from "./mcpChatContext";
import { resolveStudioConfig } from "./config";
import { buildNativeMcpServerConfig, normalizeCommercetoolsUrls } from "./mcpBootstrap";
import { MCPConnection } from "./types";

export interface ProjectMcpInitResult {
  workspaceFolder: string;
  connectionName: string;
  projectKey: string;
  files: string[];
}

const ENV_MCP_FILE = ".env.mcp";
const CURSOR_MCP_FILE = path.join(".cursor", "mcp.json");
const CURSOR_RULE_FILE = path.join(".cursor", "rules", "commerce-mcp.mdc");
const VSCODE_SETTINGS_FILE = path.join(".vscode", "settings.json");

function readJsonObject(filePath: string): Record<string, unknown> {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf-8")) as Record<string, unknown>;
  } catch {
    throw new Error(`Invalid JSON in ${path.basename(filePath)}. Fix it and try again.`);
  }
}

function writeJsonObject(filePath: string, data: Record<string, unknown>): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf-8");
}

function writeTextFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf-8");
}

function ensureGitignoreEntry(workspaceRoot: string, entry: string): boolean {
  const gitignorePath = path.join(workspaceRoot, ".gitignore");
  const normalized = entry.trim();

  if (fs.existsSync(gitignorePath)) {
    const contents = fs.readFileSync(gitignorePath, "utf-8");
    const lines = contents.split(/\r?\n/);
    const exists = lines.some((value) => {
      const trimmed = value.trim();
      return trimmed === normalized || trimmed === `${normalized}/`;
    });
    if (exists) {
      return false;
    }
    const suffix = contents.endsWith("\n") || contents.length === 0 ? "" : "\n";
    fs.writeFileSync(gitignorePath, `${contents}${suffix}${normalized}\n`, "utf-8");
    return true;
  }

  fs.writeFileSync(gitignorePath, `# Generated by Commerce MCP Studio\n${normalized}\n`, "utf-8");
  return true;
}

function buildEnvMcpContent(connection: MCPConnection, clientSecret: string): string {
  const urls = normalizeCommercetoolsUrls(connection.authUrl, connection.apiUrl);
  const tools = connection.enabledTools.join(",") || "all";
  const lines = [
    "# Commerce MCP environment — generated by Commerce MCP Studio",
    `# Connection: ${connection.name}`,
    `# Generated: ${new Date().toISOString()}`,
    "# Do not commit this file.",
    "",
    `CT_MCP_CONNECTION_NAME=${connection.name}`,
    `CT_MCP_PROJECT_KEY=${connection.projectKey}`,
    `CT_MCP_CLIENT_ID=${connection.clientId}`,
    `CT_MCP_CLIENT_SECRET=${clientSecret}`,
    `CT_MCP_AUTH_URL=${urls.authUrl}`,
    `CT_MCP_API_URL=${urls.apiUrl}`,
    `CT_MCP_TOOLS=${tools}`,
    `CT_MCP_IS_ADMIN=${connection.isAdmin || tools === "all" ? "true" : "false"}`,
    "",
    "# Aliases commonly used by commercetools tooling",
    `COMMERCETOOLS_PROJECT_KEY=${connection.projectKey}`,
    `COMMERCETOOLS_CLIENT_ID=${connection.clientId}`,
    `COMMERCETOOLS_CLIENT_SECRET=${clientSecret}`,
    `COMMERCETOOLS_AUTH_URL=${urls.authUrl}`,
    `COMMERCETOOLS_API_URL=${urls.apiUrl}`,
    "",
  ];
  return lines.join("\n");
}

export async function initProjectMcpContext(
  extensionPath: string,
  connection: MCPConnection,
  clientSecret: string
): Promise<ProjectMcpInitResult> {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  if (!workspaceFolder) {
    throw new Error("Open a workspace folder before initializing project MCP context.");
  }

  const root = workspaceFolder.uri.fsPath;
  const config = resolveStudioConfig();
  const serverId = config.nativeMcpServerId;
  const serverConfig = buildNativeMcpServerConfig(connection, clientSecret, extensionPath);
  const files: string[] = [];

  const envPath = path.join(root, ENV_MCP_FILE);
  writeTextFile(envPath, buildEnvMcpContent(connection, clientSecret));
  files.push(ENV_MCP_FILE);

  const cursorMcpPath = path.join(root, CURSOR_MCP_FILE);
  const cursorMcp = readJsonObject(cursorMcpPath);
  const mcpServers = {
    ...((cursorMcp.mcpServers as Record<string, unknown> | undefined) ?? {}),
    [serverId]: serverConfig,
  };
  writeJsonObject(cursorMcpPath, { ...cursorMcp, mcpServers });
  files.push(CURSOR_MCP_FILE);

  const vscodeSettingsPath = path.join(root, VSCODE_SETTINGS_FILE);
  const vscodeSettings = readJsonObject(vscodeSettingsPath);
  const servers = {
    ...((vscodeSettings["mcp.servers"] as Record<string, unknown> | undefined) ?? {}),
    [serverId]: serverConfig,
  };
  writeJsonObject(vscodeSettingsPath, { ...vscodeSettings, "mcp.servers": servers });
  files.push(VSCODE_SETTINGS_FILE);

  const rulePath = path.join(root, CURSOR_RULE_FILE);
  writeTextFile(rulePath, buildCommerceMcpCursorRule(connection));
  files.push(CURSOR_RULE_FILE);

  if (ensureGitignoreEntry(root, ENV_MCP_FILE)) {
    files.push(".gitignore");
  }

  return {
    workspaceFolder: workspaceFolder.name,
    connectionName: connection.name,
    projectKey: connection.projectKey,
    files,
  };
}

export async function openProjectMcpFiles(result: ProjectMcpInitResult): Promise<void> {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  if (!workspaceFolder) {
    return;
  }

  const preferred = [ENV_MCP_FILE, CURSOR_MCP_FILE, CURSOR_RULE_FILE];
  for (const relativePath of preferred) {
    if (!result.files.includes(relativePath)) {
      continue;
    }
    const uri = vscode.Uri.joinPath(workspaceFolder.uri, relativePath);
    const doc = await vscode.workspace.openTextDocument(uri);
    await vscode.window.showTextDocument(doc, { preview: false });
    break;
  }
}
